[package]
name = "map-trait"
version = "0.3.1"
authors = ["Colin Moore <colin@moore.one>"]
edition = "2018"

description = "Generic Map trait"

readme = "README.md"

keywords = ["map", "data-structure", "generic", "containers"]

categories = []

license = "MIT OR Apache-2.0"

[dependencies]
